spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      discovery:
        locator:
          enabled: false
      routes:
        - id: userProfilesPrincipalGetPatchDelete
          uri: http://pet-profiles
          predicates:
            - Path=/profiles/me
            - Method=GET,PATCH,DELETE
          filters:
            - AddPrincipalToPathFilter
        - id: userProfilesPut
          uri: http://pet-profiles
          predicates:
            - Path=/profiles/**
            - Method=PUT
        - id: serviceFunctions
          uri: http://pet-profiles
          predicates:
            - Path=/service/**
        - id: petprofiles
          uri: http://pet-profiles
          predicates:
            - Path=/pets, /pets/**, /api/v1/petprofiles/**
        - id: openapi
          uri: http://api-gateway
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /api/v1//$\{path}/api-doc
keycloak-client:
  server-url: http://keycloak/auth
