spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      discovery:
        locator:
          enabled: false
      routes:
        - id: userProfilesPrincipal
          uri: http://pet-profiles
          predicates:
            - Path=/api/v1/profiles/me, /api/v1/service/profile/me/**, /api/v1/service/pets/**
            - Method=GET,PUT,POST,PATCH,DELETE
          filters:
            - AddPrincipalToPathFilter
        - id: petprofiles
          uri: http://pet-profiles
          predicates:
            - Path=/api/v1/pets, /api/v1/pets/**, /api/v1/petprofiles/**, /api/v1/profiles/**
        - id: openapi
          uri: http://api-gateway
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /api/v1//$\{path}/api-doc
keycloak-client:
  server-url: http://keycloak/auth
